# Generated by Django 5.0.7 on 2024-11-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offender', '0002_alter_personalinformation_offender_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_investigator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_judge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_offender',
            field=models.BooleanField(default=False),
        ),
    ]
