# Generated by Django 5.0.7 on 2024-11-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offender', '0003_user_is_investigator_user_is_judge_user_is_offender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_offender',
        ),
    ]
